const cars = [
    {
      id: 1,
      image: "2005-MITSUBISHI-ENDEAVOR.jpg",
      year: "2005",
      make: "Mitsubishi",
      model: "Endevor",
      price: 2700,
      mileage: 154000,
      transmission: "Automatic",
    },
    {
      id: 2,
      image: "2003-SATURN-SATURN-L-SERIES.jpg",
      year: "2003",
      make: "Saturn",
      model: "L Series",
      price: 2500,
      mileage: 210000,
      transmission: "Automatic",
    },
    {
      id: 3,
      image: "2008-MAZDA-MAZDA-3.jpg",
      year: "2008",
      make: "Mazda",
      model: "3",
      price: 3800,
      mileage: 182000,
      transmission: "Automatic",
    },
    {
      id: 4,
      image: "2005-MERCURY-SABLE.jpg",
      year: "2005",
      make: "Mercury",
      model: "Sable",
      price: 1900,
      mileage: 139000,
      transmission: "Automatic",
    },
    {
      id: 5,
      image: "2016-DODGE-CHALLENGER-HELLCAT.jpg",
      year: "2016",
      make: "Dodge",
      model: "Challenger",
      price: 5600,
      mileage: 98000,
      transmission: "Manual",
    },
    {
      id: 6,
      image: "2016-PORSCHE-CAYENNE.jpg",
      year: "2016",
      make: "Porsche",
      model: "Cayenne",
      price: 4800,
      mileage: 132553,
      transmission: "Automatic",
    },
  ];

  export default cars; 